### ISSUE TITLE
Following the readme steps leads to errors

### ISSUE THREAD

**Issue by alexbouchardd** [hookdeck/hookdeck-vercel-example#1]
I've ran into 2 issues following the readme.

1. All my Vercel deployments were protected by default, so the test cURL request was hitting an authentication page rather than hitting the `/api/webhooks` URL. I had to disable this option in Vercel project settings manually.

<img width="936" alt="Screenshot 2024-04-27 at 12 04 15 PM" src="https://github.com/hookdeck/hookdeck-vercel-example/assets/2049224/afe0adfe-4820-4d37-80d8-e5645d3a22a7">

2. The local env variables were not applied to the production env, I needed to manually add the config in the dashboard (afaik)

3. I get a 422 when deploying, seemingly because the `url` is missing `https://`?
<img width="1244" alt="Screenshot 2024-04-27 at 12 08 51 PM" src="https://github.com/hookdeck/hookdeck-vercel-example/assets/2049224/8002cd16-2cd2-4fba-98d6-b13dfba6a9e0">

**Comment by leggetter** [comment]
> All my Vercel deployments were protected by default, so the test cURL request was hitting an authentication page rather than hitting the /api/webhooks URL. I had to disable this option in Vercel project settings manually.

The production deployment isn't protected by default. But you need to get the URL for that from the Vercel project dashboard. I've updated the details in https://github.com/hookdeck/hookdeck-vercel-example/commit/708ed06757a07112e9afee1af45ae645adbf343c

Updated further in https://github.com/hookdeck/hookdeck-vercel-example/commit/ac8fc15b2ba69444fd1fd8307396110ee957b40e.

> The local env variables were not applied to the production env, I needed to manually add the config in the dashboard (afaik)

The instructions in the README about adding the env vars from the `vercel` CLI were incorrect. Also fixed in https://github.com/hookdeck/hookdeck-vercel-example/commit/708ed06757a07112e9afee1af45ae645adbf343c

> I get a 422 when deploying, seemingly because the url is missing https://?

I haven't seen this and can't replicate it.
